os: osx
language: objective-c
osx_image: xcode11.3
xcode_project: ResourceCryptor.xcodeproj # path to your xcodeproj folder
xcode_scheme: ResourceCryptor
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone X

script:
- carthage update --platform iOS
- xcodebuild -scheme ResourceCryptorTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=13.2' test

#env:
#- DESTINATION="OS=13.0,name=iPhone 11" SCHEME="ResourceCryptor" SDK=iphonesimulator CODECOV_TOKEN=e3f38d6b-fc35-4e17-8478-dc2a50d1faff

notifications:
  email:
    - 781232284@qq.com
