coverage:
  status:
    project:
      default: off
      ResourceCryptor:
        flags: ResourceCryptor
        target: 100%

flags:
  # filter the folder(s) you wish to measure by that flag
  KeychainWrapper:
    # only include files in the backend folder
    paths:
      - ResourceCryptor/
